### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [umnsec/cheq#1]
I would like to point out that identifiers like “[`_ANALYZER_GLOBAL_H`](https://github.com/umnsec/cheq/blob/513822306d40a1753a2ae5626db0bdbdebdbcb7e/analyzer/src/lib/Analyzer.h#L1 "Update candidate")” and “[`_CALL_GRAPH_H`](https://github.com/umnsec/cheq/blob/513822306d40a1753a2ae5626db0bdbdebdbcb7e/analyzer/src/lib/CallGraph.h#L1 "Another update candidate")” [do eventually not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not declare an identifier which is reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by ghost** [comment]
Thanks for the link and identifying the issue. We changed the header files to suit the standard for the future.

**Comment by elfring** [comment]
Thanks for [the adjustment of affected include guards](https://github.com/umnsec/cheq/commit/59b694b7c6efcda8b667f8843ad37c465f09641b#diff-4066950429a7584c8710d4b16c19f7e7L1 "Renaming of include guards").
