### ISSUE TITLE
Fix typos

### ISSUE THREAD

**Issue by elfring** [umnsec/cheq#3]
I have accidentally noticed a few typos.
* https://github.com/umnsec/cheq/blob/9360f7d6c2e35ccaacbb2ac17705587beb43adce/README.md#run-the-cheq-analyzer
* https://github.com/umnsec/cheq/blob/513822306d40a1753a2ae5626db0bdbdebdbcb7e/analyzer/src/lib/Analyzer.cc#L3

Would you like to adjust affected places?

**Comment by ghost** [comment]
Thanks for identifying the typo, we fixed this issue.

**Comment by elfring** [comment]
[A small correction would be helpful also at another place](https://github.com/umnsec/cheq/blob/9360f7d6c2e35ccaacbb2ac17705587beb43adce/README.md#run-the-cheq-analyzer "Fixing a command").
Will similar changes influence any more software components?
