### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [umnsec/cheq#4]
* Would you like to [add more error handling for return values](https://github.com/umnsec/cheq/blob/59b694b7c6efcda8b667f8843ad37c465f09641b/analyzer/src/lib/Analyzer.cc#L144 "Update candidate: main()") from calls of a function like [strdup()](https://pubs.opengroup.org/onlinepubs/9699919799/functions/strdup.html "Duplicate a string.")?
* Can your analysis tool point similar source code places out for further software development considerations?

**Comment by kengiter** [comment]
For customization of determining error codes, please refer to function `isValueErrno`.

https://github.com/umnsec/cheq/blob/94871abc39fb6ccbcdf59bafc8ba930a6dc0e662/analyzer/src/lib/SecurityChecks.cc#L47

**Comment by elfring** [comment]
How do you think about to improve [static source code analysis](https://en.wikipedia.org/wiki/List_of_tools_for_static_code_analysis#C.2C_C.2B.2B "Tools for code analysis") also for this software?
